module(
    name = "language_duel_lab",
    version = "1.0.0",
)

bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_qt", version = "0.0.6")

qt = use_extension("@rules_qt//extension:qt.bzl", "fetch")

qt.install(
    version = "6.8.3",
)

use_repo(
    qt,
    "qt_linux_x86_64",
    "qt_mac_aarch64",
    "qt_windows_x86_64",
)

register_toolchains("@rules_qt//tools:all")
