#include "database.h"

//жёстка нагенерено
inline void Insert() {
    auto& db = Database::GetInstance();

    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Собака", "Dog", "3 letters, rhymes with 'log'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Дом", "House", "Starts with 'H', opposite of 'outside'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Вода", "Water", "Starts with 'W', essential for life"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Огонь", "Fire", "4 letters, opposite of 'ice'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Книга", "Book", "Starts with 'B', you read it"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Рука", "Hand", "Part of the body, rhymes with 'land'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Ночь", "Night", "Opposite of 'day', starts with 'N'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Хлеб", "Bread", "Starts with 'B', made from flour"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Кот", "Cat", "3 letters, rhymes with 'hat'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Солнце", "Sun", "The star in our solar system"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Яблоко", "Apple", "Fruit, name of a tech company"));      
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Стул", "Chair", "Furniture with 4 legs, starts with 'CH'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Окно", "Window", "Glass opening in wall, starts with 'W'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Цветок", "Flower", "Grows in garden, starts with 'F'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Птица", "Bird", "Flies in sky, rhymes with 'word'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Молоко", "Milk", "White drink, starts with 'M'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Школа", "School", "Place for learning, starts with 'S'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Дерево", "Tree", "Has leaves and bark, starts with 'T'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Low, Task::NotDone, "Машина", "Car", "Vehicle with wheels, 3 letters"));

    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Разработчик", "Developer", "Writes code, starts with 'D'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Путешествие", "Journey", "Synonym of 'trip', starts with 'J'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Обсуждение", "Discussion", "Formal talk, ends with '-tion'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Бегать", "Run", "3 letters, faster than walking"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Говорить", "Speak", "Starts with 'S', synonym of 'talk'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Понять", "Understand", "Starts with 'U', means 'get the meaning'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Работа", "Work", "Starts with 'W', opposite of 'rest'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Проблема", "Problem", "Starts with 'P', synonym of 'issue'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Счастливый", "Happy", "Starts with 'H', opposite of 'sad'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Внезапно", "Suddenly", "Starts with 'S', means 'without warning'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Возможность", "Opportunity", "Starts with 'O', synonym of 'chance'")); 
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Писать", "Write", "Opposite of 'read', starts with 'W'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Слушать", "Listen", "Pay attention to sounds, starts with 'L'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Красивый", "Beautiful", "Opposite of 'ugly', starts with 'B'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Быстрый", "Fast", "Opposite of 'slow', rhymes with 'last'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Трудный", "Difficult", "Synonym of 'hard', starts with 'D'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Покупать", "Buy", "Opposite of 'sell', 3 letters"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Продавать", "Sell", "Opposite of 'buy', starts with 'S'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::Medium, Task::NotDone, "Путешествовать", "Travel", "Go to new places, starts with 'T'"));

    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Беспрецедентный", "Unprecedented", "Means 'never happened before', starts with 'Un-'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Подразумевать", "Imply", "To suggest indirectly, 4 letters"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Неоднозначность", "Ambiguity", "Lack of clarity, starts with 'Ambi-'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Устойчивость", "Resilience", "Ability to recover, starts with 'R-'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Подтверждение", "Confirmation", "Starts with 'C', formal agreement"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Недостаток", "Drawback", "Starts with 'D', synonym of 'disadvantage'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Осуществлять", "Implement", "Starts with 'I', means 'put into action'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Убедительный", "Persuasive", "Starts with 'P', means 'convincing'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Предположение", "Assumption", "Starts with 'A', synonym of 'guess'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Взаимодействие", "Interaction", "Starts with 'I', communication between things"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Осознание", "Awareness", "Starts with 'A', means 'conscious knowledge'"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Приспособляемость", "Adaptability", "Starts with 'A', ability to adjust"));  
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Ответственность", "Responsibility", "Starts with 'R', being accountable"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Влияние", "Influence", "Power to affect, starts with 'I'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Окружающая среда", "Environment", "Starts with 'E', nature around us"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Исследование", "Research", "Scientific study, starts with 'R'"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Технология", "Technology", "Starts with 'T', tools and machines"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Эффективный", "Efficient", "Starts with 'E', doing things well"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Сотрудничество", "Collaboration", "Starts with 'C', working together"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Удовлетворение", "Satisfaction", "Starts with 'S', feeling of pleasure"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Непреодолимый", "Insurmountable", "Starts with 'I', cannot be overcome"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Неоднозначный", "Ambiguous", "Starts with 'A', unclear meaning"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Самоотверженный", "Selfless", "Starts with 'S', putting others first"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Непримиримый", "Irreconcilable", "Starts with 'I', cannot be resolved"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Предвзятость", "Bias", "Starts with 'B', unfair preference"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Перспективный", "Promising", "Starts with 'P', likely to succeed"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Конкурентоспособный", "Competitive", "Starts with 'C', able to compete"));
    db.InsertTask(std::make_unique<TranslationTask>(Task::High, Task::NotDone, "Несоответствие", "Discrepancy", "Starts with 'D', inconsistency"));
    
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "She ___ TV every evening.", QStringList{"watch", "watches", "watching"}, 1, "Add -s for he/she/it"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "My parents ___ in Moscow.", QStringList{"lives", "live", "living"}, 1, "Plural subject = base verb"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "This is ___ orange.", QStringList{"a", "an", "the"}, 1, "Use 'an' before vowel sounds"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "I need ___ new phone.", QStringList{"a", "an", "the"}, 0, "Use 'a' before consonant sounds"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "There are three ___ on the table.", QStringList{"book", "books", "bookes"}, 1, "Regular plural adds -s"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "The ___ are playing outside.", QStringList{"child", "childs", "children"}, 2, "Irregular plural form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "This coffee is very ___.", QStringList{"hotter", "hot", "hottest"}, 1, "Use base adjective form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "My brother ___ in London.", QStringList{"live", "lives", "living"}, 1, "3rd person singular verb ending"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "There ___ many people at the park.", QStringList{"is", "are", "be"}, 1, "Plural noun requires plural verb"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "I ___ to the store yesterday.", QStringList{"go", "went", "gone"}, 1, "Past simple of 'go'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "She ___ reading a book now.", QStringList{"is", "are", "am"}, 0, "Present continuous auxiliary for 'she'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "We ___ seen this movie before.", QStringList{"has", "have", "had"}, 1, "Plural subject with present perfect"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "She ___ coffee every morning.", QStringList{"drink", "drinks", "drinking"}, 1, "3rd person singular needs -s"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "They ___ football on weekends.", QStringList{"plays", "play", "playing"}, 1, "Plural subject = base verb"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "He ___ his homework yesterday.", QStringList{"finished", "finishes", "finish"}, 0, "Regular past tense (-ed)"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "We ___ to Paris last summer.", QStringList{"go", "went", "gone"}, 1, "Irregular past 'go→went'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "This is ___ useful book.", QStringList{"a", "an", "the"}, 0, "'Useful' starts with consonant sound"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "She ___ to school every day.", QStringList{"go", "goes", "going"}, 1, "Third person singular needs -s"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "There ___ three apples on the table.", QStringList{"is", "are", "be"}, 1, "Plural noun requires plural verb"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "I ___ breakfast at 7 am yesterday.", QStringList{"eat", "eaten", "ate"}, 2, "Past simple of 'eat'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Low, Task::NotDone, "This is ___ book.", QStringList{"a", "an", "the"}, 0, "Before consonant sound"));

    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "I'm good ___ math.", QStringList{"at", "in", "with"}, 0, "Fixed preposition"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "We arrived ___ London yesterday.", QStringList{"at", "to", "in"}, 2, "Cities use 'in'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "Please ___ the lights before leaving.", QStringList{"turn off", "turn on", "turn up"}, 0, "Meaning 'switch off'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "I need to ___ my application today.", QStringList{"fill in", "fill out", "fill up"}, 1, "Meaning 'complete'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "Right now, they ___ dinner.", QStringList{"cooks", "are cooking", "cooked"}, 1, "Action happening now"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "Look! It ___ outside.", QStringList{"snows", "is snowing", "snowing"}, 1, "Temporary situation"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "We ___ a great film last night.", QStringList{"see", "saw", "seen"}, 1, "Irregular past form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "She ___ her keys yesterday.", QStringList{"loses", "lost", "losed"}, 1, "Regular past (-ed)"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "I ___ never ___ sushi.", QStringList{"have...eat", "have...ate", "have...eaten"}, 2, "Past participle required"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "___ you ever ___ to Japan?", QStringList{"Did...go", "Have...been", "Do...go"}, 1, "Experience question"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "You ___ stop when the light is red.", QStringList{"could", "must", "might"}, 1, "Strong obligation"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "___ I borrow your pen?", QStringList{"May", "Should", "Would"}, 0, "Asking permission"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "This test was ___ than the last one.", QStringList{"difficult", "more difficult", "most difficult"}, 1, "Comparative form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "She is ___ student in our class.", QStringList{"the taller", "the tallest", "tallest"}, 1, "Superlative form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "By 5 PM, I ___ my work.", QStringList{"will finish", "will have finished", "finish"}, 1, "Future perfect for completed action"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "You ___ wear a uniform at this school.", QStringList{"must", "could", "might"}, 0, "Obligation modal"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "If it rains, we ___ inside.", QStringList{"stay", "will stay", "would stay"}, 1, "1st conditional for real possibility"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "I wish I ___ how to swim.", QStringList{"know", "knew", "had known"}, 1, "Present unreal wish"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "The train ___ when we arrived.", QStringList{"already left", "had already left", "has left"}, 1, "Past perfect for earlier action"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "Look! They ___ a new house.", QStringList{"build", "are building", "built"}, 1, "Action happening now"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "You ___ smoke here; it's prohibited.", QStringList{"mustn't", "don't have to", "might not"}, 0, "Prohibition = mustn't"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "This test is ___ than the last one.", QStringList{"difficult", "more difficult", "most difficult"}, 1, "Comparative for long adjectives"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "I ___ this movie before.", QStringList{"see", "saw", "have seen"}, 2, "Experience = present perfect"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "By next year, I ___ here for five years.", QStringList{"will work", "will be working", "will have worked"}, 2, "Future perfect for duration"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "You ___ see a doctor if your headache persists.", QStringList{"should", "would", "might"}, 0, "Advice modal"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "When I arrived, they ___ dinner.", QStringList{"had", "were having", "have had"}, 1, "Past continuous for interrupted action"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::Medium, Task::NotDone, "If I ___ you, I would apologize.", QStringList{"am", "were", "would be"}, 1, "Second conditional form"));

    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Not until midnight ___ the results.", QStringList{"we knew", "did we know", "we did know"}, 1, "Negative adverbial inversion"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The proposal ___ by the committee right now.", QStringList{"is considered", "is being considered", "has been considered"}, 1, "Present continuous passive"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Had I known earlier, I ___ differently.", QStringList{"would act", "would have acted", "will act"}, 1, "3rd conditional structure"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "___ the weather was bad, we enjoyed the trip.", QStringList{"Although", "Despite", "However"}, 0, "Conjunction for contrast"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The jury ___ divided in their opinions.", QStringList{"is", "are", "were"}, 0, "Collective noun as single unit"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "___ I suggest we take a break?", QStringList{"Can", "May", "Shall"}, 2, "Suggestion modal"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "It's time you ___ responsibility.", QStringList{"take", "took", "will take"}, 1, "Unreal past structure"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "No sooner ___ I spoken than he replied.", QStringList{"had", "did", "have"}, 0, "Inversion with 'no sooner'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Were I you, I ___ reconsider.", QStringList{"will", "would", "would have"}, 1, "Conditional inversion"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Such ___ the circumstances that we had to act fast.", QStringList{"was", "were", "is"}, 1, "Inversion after 'such'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Never ___ such a beautiful sunset.", QStringList{"I saw", "saw I", "have I seen"}, 2, "Negative adverbial → inversion"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "If you ___ harder, you would have passed.", QStringList{"worked", "had worked", "would work"}, 1, "Mixed conditional (past + present result)"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "___ was the music that annoyed me.", QStringList{"It", "There", "What"}, 0, "Cleft structure 'It was... that'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "I suggest that he ___ earlier.", QStringList{"comes", "come", "will come"}, 1, "Subjunctive = base verb"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The project ___ by the team last month.", QStringList{"completed", "was completed", "has completed"}, 1, "Past passive = was + V3"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "If I ___ richer, I would travel more.", QStringList{"am", "were", "had been"}, 1, "Unreal present = if + past simple"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "After she ___ dinner, she watched TV.", QStringList{"had", "had had", "has had"}, 1, "Earlier action = past perfect"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The man ___ car was stolen called the police.", QStringList{"who", "whose", "whom"}, 1, "Possessive relative pronoun"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Not only ___ late, but he also forgot the documents.", QStringList{"he was", "was he", "he is"}, 1, "Inversion after 'not only'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The report ___ by the time the meeting starts.", QStringList{"will finish", "will be finished", "will have been finished"}, 2, "Future perfect passive"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "Had I known about the problem, I ___ differently.", QStringList{"would act", "would have acted", "will act"}, 1, "Third conditional form"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "___ his brilliant ideas, the project failed.", QStringList{"Despite", "Although", "Nevertheless"}, 0, "Preposition for contrast"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "The committee ___ divided in their opinions.", QStringList{"is", "are", "were"}, 0, "Collective noun as single unit"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "___ I make myself clear?", QStringList{"Do", "Have", "Am"}, 0, "Do-support for main verb 'make'"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "It's high time you ___ that report.", QStringList{"finished", "finish", "will finish"}, 0, "'It's time' + past simple for unreal past"));
    db.InsertTask(std::make_unique<GrammarTask>(Task::High, Task::NotDone, "No sooner ___ I arrived than the meeting began.", QStringList{"had", "did", "have"}, 0, "Inversion with 'no sooner'"));
}