#include "vectors.h"

std::vector<QString> eng = {
    "The sun is shining brightly today.",
    "I love reading books in my free time.",
    "She is learning to play the piano.",
    "We usually have dinner at 7 PM.",
    "He works as a doctor in a big hospital.",
    "They traveled to Spain last summer.",
    "My favorite color is blue.",
    "The cat is sleeping on the sofa.",
    "She speaks three languages fluently.",
    "I need to buy some groceries.",
    "The movie starts at 9 o'clock.",
    "He forgot his keys at home.",
    "We are planning a trip to the mountains.",
    "She always wears a red scarf.",
    "The children are playing in the park.",
    "This coffee is too hot to drink.",
    "I have a meeting at 3 PM.",
    "He fixed the broken chair.",
    "She doesn't like spicy food.",
    "The train arrives at noon.",
    "My brother is taller than me.",
    "We watched a great movie yesterday.",
    "The flowers need more water.",
    "She bought a new dress for the party.",
    "I can't find my phone.",
    "The weather is getting colder.",
    "He enjoys hiking in the forest.",
    "The book was very interesting.",
    "She has a beautiful voice.",
    "I'll call you later.",
    "The restaurant serves delicious pizza.",
    "He lost his wallet.",
    "We need to clean the house.",
    "She is afraid of spiders.",
    "The sky is full of stars tonight.",
    "I finished my homework early.",
    "He gave her a birthday present.",
    "The dog barked loudly.",
    "She writes in her diary every day.",
    "I prefer tea over coffee.",
    "The baby is crying.",
    "He runs every morning.",
    "We visited the museum last weekend.",
    "The cake tastes amazing.",
    "She is waiting for the bus.",
    "I need to take a break.",
    "He painted the wall blue.",
    "The meeting was canceled.",
    "She dreams of becoming a singer.",
    "I'll meet you at the cafe."
};

std::vector<QString> rus = {
    "Сегодня ярко светит солнце.",
    "Я люблю читать книги в свободное время.",
    "Она учится играть на пианино.",
    "Мы обычно ужинаем в 7 вечера.",
    "Он работает врачом в большой больнице.",
    "Они ездили в Испанию прошлым летом.",
    "Мой любимый цвет — синий.",
    "Кот спит на диване.",
    "Она свободно говорит на трёх языках.",
    "Мне нужно купить продукты.",
    "Фильм начинается в 9 часов.",
    "Он забыл ключи дома.",
    "Мы планируем поездку в горы.",
    "Она всегда носит красный шарф.",
    "Дети играют в парке.",
    "Этот кофе слишком горячий, чтобы пить.",
    "У меня встреча в 3 часа дня.",
    "Он починил сломанный стул.",
    "Она не любит острую еду.",
    "Поезд прибывает в полдень.",
    "Мой брат выше меня.",
    "Вчера мы смотрели отличный фильм.",
    "Цветам нужно больше воды.",
    "Она купила новое платье для вечеринки.",
    "Я не могу найти свой телефон.",
    "Погода становится холоднее.",
    "Ему нравится ходить в походы в лес.",
    "Книга была очень интересной.",
    "У неё красивый голос.",
    "Я позвоню тебе позже.",
    "В этом ресторане готовят вкусную пиццу.",
    "Он потерял кошелёк.",
    "Нам нужно убраться в доме.",
    "Она боится пауков.",
    "Сегодня ночью небо усыпано звёздами.",
    "Я рано закончил домашнюю работу.",
    "Он подарил ей подарок на день рождения.",
    "Собака громко лаяла.",
    "Она пишет в дневнике каждый день.",
    "Я предпочитаю чай кофе.",
    "Ребёнок плачет.",
    "Он бегает каждое утро.",
    "Мы ходили в музей на прошлых выходных.",
    "Торт потрясающе вкусный.",
    "Она ждёт автобус.",
    "Мне нужно сделать перерыв.",
    "Он покрасил стену в синий цвет.",
    "Встречу отменили.",
    "Она мечтает стать певицей.",
    "Я встречу тебя в кафе."
};

std::vector<QString> ques = {
    "She usually _______ (go) to the gym after work.",
    "They _______ (watch) a movie when the power went out.",
    "He _______ (finish) his report by tomorrow morning.",
    "By the time we arrived, they _______ (already eat) dinner.",
    "I _______ (live) here for ten years next month.",
    "You _______ (not park) here; it's a restricted area.",
    "_______ I borrow your pen for a moment?",
    "He _______ be very tired after such a long journey.",
    "They _______ have called if they were going to be late.",
    "You _______ see the doctor if your condition worsens.",
    "The window _______ (break) by the strong wind.",
    "The new bridge _______ (expect) to be completed next year.",
    "The thief _______ (catch) by the police last night.",
    "This book _______ (write) by a famous author.",
    "The meeting _______ (hold) in the main hall.",
    "She is _______ honest woman.",
    "They live in _______ small village in the mountains.",
    "_______ sun rises in the east.",
    "He is _______ university student.",
    "We went to _______ beach yesterday.",
    "The book is _______ the table.",
    "They arrived _______ London yesterday.",
    "She is interested _______ learning new languages.",
    "The cat jumped _______ the sofa.",
    "He waited _______ her for half an hour.",
    "_______ (I) went to the store yesterday.",
    "This is _______ (they) new car.",
    "She gave the book to _______ (he).",
    "They blamed _______ (themselves) for the mistake.",
    "_______ (who) is at the door?",
    "She likes tea _______ coffee.",
    "He studied hard _______ he failed the exam.",
    "I will go to the party _______ I finish my work.",
    "It was raining, _______ we decided to stay home.",
    "_______ you are tired, you should take a rest.",
    "My sister _______ (like) to read novels.",
    "The students _______ (study) hard for the test.",
    "There _______ (be) a big tree in the garden.",
    "Neither John nor Mary _______ (want) to go.",
    "Each of the boys _______ (have) a bicycle."
};

std::vector<std::vector<QString>> answer {
{"a) goes", "b) going", "c) went", "d) gone"},
{"a) watched", "b) were watching", "c) are watching", "d) watch"},
{"a) will finish", "b) finishes", "c) is finishing", "d) finished"},
                                         {"a) ate", "b) had eaten", "c) have eaten", "d) are eating"},
                                         {"a) will live", "b) will be living", "c) have lived", "d) lived"},
                                         {"a) mustn't", "b) shouldn't", "c) wouldn't", "d) couldn't"},
                                         {"a) Can", "b) Should", "c) Would", "d) Might"},
                                         {"a) must", "b) can", "c) will", "d) may"},
                                         {"a) should", "b) could", "c) would", "d) might"},
                                         {"a) ought to", "b) can", "c) will", "d) may"},
                                         {"a) broke", "b) was broken", "c) has broken", "d) is breaking"},
                                         {"a) expects", "b) is expected", "c) will expect", "d) expected"},
                                         {"a) caught", "b) was caught", "c) has caught", "d) is catching"},
                                         {"a) writes", "b) is written", "c) wrote", "d) has written"},
                                         {"a) holds", "b) will be held", "c) is holding", "d) held"},
                                         {"a) a", "b) an", "c) the", "d) - (no article)"},
                                         {"a) a", "b) an", "c) the", "d) - (no article)"},
                                         {"a) A", "b) An", "c) The", "d) - (no article)"},
                                         {"a) a", "b) an", "c) the", "d) - (no article)"},
                                         {"a) a", "b) an", "c) the", "d) - (no article)"},
                                         {"a) in", "b) on", "c) at", "d) under"},
                                         {"a) in", "b) on", "c) at", "d) to"},
                                         {"a) in", "b) on", "c) at", "d) for"},
                                         {"a) over", "b) above", "c) onto", "d) across"},
                                         {"a) to", "b) for", "c) at", "d) with"},
                                         {"a) Me", "b) I", "c) My", "d) Mine"},
                                         {"a) them", "b) their", "c) theirs", "d) they're"},
                                         {"a) him", "b) his", "c) he", "d) himself"},
                                         {"a) they", "b) them", "c) theirselves", "d) themselves"},
                                         {"a) Whom", "b) Whose", "c) Who", "d) Which"},
                                         {"a) but", "b) or", "c) and", "d) so"},
                                         {"a) because", "b) although", "c) so", "d) if"},
                                         {"a) until", "b) unless", "c) as soon as", "d) while"},
                                         {"a) but", "b) so", "c) because", "d) if"},
                                         {"a) If", "b) But", "c) Or", "d) So"},
                                         {"a) like", "b) likes", "c) liking", "d) liked"},
                                         {"a) studies", "b) is studying", "c) study", "d) studied"},
                                         {"a) is", "b) are", "c) am", "d) were"},
                                         {"a) want", "b) wants", "c) wanting", "d) wanted"},
                                         {"a) have", "b) has", "c) having", "d) had"}
};

std::vector<int> variants = {1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 3, 1, 3, 2, 1, 1, 3, 2, 2, 2, 1, 4, 3, 3, 2, 3, 2, 1, 2, 3, 1, 2, 2};





