#include "exercisedata.h"

ExerciseData::ExerciseData() {
    initializeData();
}

void ExerciseData::initializeData() {
    difficultyLevels << "Easy" << "Medium" << "Hard";

    translationTasksMap["Easy"] = {
        {1, "Hello", "Привет", ""}, {2, "Goodbye", "Пока", ""}, {3, "Thank you", "Спасибо", ""}, {4, "Please", "Пожалуйста", ""}, {5, "Yes", "Да", ""},
        {6, "No", "Нет", ""}, {7, "Good morning", "Доброе утро", ""}, {8, "Good evening", "Добрый вечер", ""}, {9, "How are you?", "Как дела?", ""}, {10, "My name is", "Меня зовут", ""},
        {11, "Water", "Вода", ""}, {12, "Food", "Еда", ""}, {13, "House", "Дом", ""}, {14, "Cat", "Кошка", ""}, {15, "Dog", "Собака", ""},
        {16, "Book", "Книга", ""}, {17, "Friend", "Друг", ""}, {18, "To read", "Читать", ""}, {19, "To eat", "Есть", ""}, {20, "To sleep", "Спать", ""},
        {21, "Big", "Большой", ""}, {22, "Small", "Маленький", ""}, {23, "Happy", "Счастливый", ""}, {24, "Sad", "Грустный", ""}, {25, "Today", "Сегодня", ""},
        {26, "Tomorrow", "Завтра", ""}, {27, "Yesterday", "Вчера", ""}, {28, "One", "Один", ""}, {29, "Two", "Два", ""}, {30, "Three", "Три", ""},
        {31, "Red", "Красный", ""}, {32, "Blue", "Синий", ""}, {33, "Green", "Зеленый", ""}, {34, "Sun", "Солнце", ""}, {35, "Moon", "Луна", ""},
        {36, "Car", "Машина", ""}, {37, "Tree", "Дерево", ""}, {38, "Flower", "Цветок", ""}, {39, "Child", "Ребенок", ""}, {40, "Man", "Мужчина", ""},
        {41, "Woman", "Женщина", ""}, {42, "School", "Школа", ""}, {43, "Teacher", "Учитель", ""}, {44, "Student", "Студент", ""}, {45, "City", "Город", ""},
        {46, "Day", "День", ""}, {47, "Night", "Ночь", ""}, {48, "Love", "Любовь", ""}, {49, "Hate", "Ненавидеть", ""}, {50, "Music", "Музыка", ""}
    };
    grammarTasksMap["Easy"] = {
        {1, "She ___ to the park yesterday.", {"go", "goes", "went", "gone"}, "went", ""}, {2, "They ___ watching TV now.", {"is", "are", "am", "be"}, "are", ""}, {3, "I ___ a student.", {"is", "are", "am", "be"}, "am", ""}, {4, "He ___ a doctor.", {"is", "are", "am", "be"}, "is", ""}, {5, "We ___ friends.", {"is", "are", "am", "be"}, "are", ""},
        {6, "This ___ my car.", {"is", "are", "was", "were"}, "is", ""}, {7, "It ___ raining.", {"is", "are", "am", "be"}, "is", ""}, {8, "I ___ coffee.", {"like", "likes", "liking", "is liking"}, "like", ""}, {9, "She ___ apples.", {"like", "likes", "liking", "is liking"}, "likes", ""}, {10, "They ___ English.", {"speak", "speaks", "speaking", "is speaking"}, "speak", ""},
        {11, "My brother ___ tall.", {"is", "are", "am", "be"}, "is", ""}, {12, "There ___ a book on the table.", {"is", "are", "was", "were"}, "is", ""}, {13, "There ___ two cats.", {"is", "are", "was", "were"}, "are", ""}, {14, "___ you like tea?", {"Do", "Does", "Is", "Are"}, "Do", ""}, {15, "She ___ not like milk.", {"do", "does", "is", "are"}, "does", ""},
        {16, "He ___ happy yesterday.", {"is", "are", "was", "were"}, "was", ""}, {17, "They ___ at home last night.", {"is", "are", "was", "were"}, "were", ""}, {18, "I ___ to school every day.", {"go", "goes", "went", "am going"}, "go", ""}, {19, "What ___ your name?", {"is", "are", "do", "does"}, "is", ""}, {20, "___ is my pencil.", {"This", "These", "That", "Those"}, "This", ""},
        {21, "She ___ playing the piano at the moment.", {"is", "are", "am", "be"}, "is", ""}, {22, "I ___ a new phone last week.", {"buy", "buys", "bought", "buying"}, "bought", ""}, {23, "Look! The bird ___.", {"fly", "flies", "is flying", "flew"}, "is flying", ""}, {24, "___ old are you?", {"What", "How", "Who", "Which"}, "How", ""}, {25, "He doesn't ___ meat.", {"eat", "eats", "eating", "ate"}, "eat", ""},
        {26, "My parents ___ in London.", {"live", "lives", "living", "lived"}, "live", ""}, {27, "This is ___ apple.", {"a", "an", "the", "some"}, "an", ""}, {28, "There are ___ books on the shelf.", {"a", "an", "the", "some"}, "some", ""}, {29, "Can you ___ me?", {"help", "helps", "helping", "helped"}, "help", ""}, {30, "The children ___ in the garden.", {"play", "plays", "are playing", "played"}, "are playing", ""},
        {31, "I usually ___ up at 7 AM.", {"get", "gets", "am getting", "got"}, "get", ""}, {32, "___ they go to the cinema yesterday?", {"Do", "Does", "Did", "Are"}, "Did", ""}, {33, "She ___ got blue eyes.", {"has", "have", "is", "are"}, "has", ""}, {34, "We ___ late for the meeting.", {"is", "are", "am", "be"}, "are", ""}, {35, "It ___ cold today.", {"is", "are", "am", "be"}, "is", ""},
        {36, "What time ___ it?", {"is", "are", "do", "does"}, "is", ""}, {37, "My mother ___ delicious cakes.", {"make", "makes", "making", "made"}, "makes", ""}, {38, "The sun ___ in the east.", {"rise", "rises", "rising", "rose"}, "rises", ""}, {39, "Fish ___ in water.", {"live", "lives", "living", "lived"}, "live", ""}, {40, "He ___ homework now.", {"do", "does", "is doing", "did"}, "is doing", ""},
        {41, "___ a nice day!", {"Have", "Has", "Is", "Are"}, "Have", ""}, {42, "They ___ to music yesterday evening.", {"listen", "listens", "listened", "listening"}, "listened", ""}, {43, "The flowers ___ beautiful.", {"is", "are", "am", "be"}, "are", ""}, {44, "I ___ to see you soon.", {"hope", "hopes", "hoping", "hoped"}, "hope", ""}, {45, "She always ___ the truth.", {"tell", "tells", "telling", "told"}, "tells", ""},
        {46, "Where ___ your keys?", {"is", "are", "do", "does"}, "are", ""}, {47, "We ___ not go out tonight.", {"do", "does", "did", "will"}, "will", ""}, {48, "My dog ___ black and white.", {"is", "are", "has", "have"}, "is", ""}, {49, "The train ___ at 9 AM.", {"leave", "leaves", "leaving", "left"}, "leaves", ""}, {50, "___ this book interesting?", {"Is", "Are", "Do", "Does"}, "Is", ""}
    };
    timeLimits["Easy"] = 120;

    translationTasksMap["Medium"] = {
        {1, "What is your name?", "Как тебя зовут?", ""}, {2, "I am learning C++.", "Я учу C++.", ""}, {3, "The weather is nice today.", "Сегодня хорошая погода.", ""}, {4, "How old are you?", "Сколько тебе лет?", ""}, {5, "Where do you live?", "Где ты живешь?", ""},
        {6, "I like to travel.", "Я люблю путешествовать.", ""}, {7, "Can you help me?", "Можешь мне помочь?", ""}, {8, "What time is it?", "Который час?", ""}, {9, "I need a doctor.", "Мне нужен врач.", ""}, {10, "This is very interesting.", "Это очень интересно.", ""},
        {11, "I don't understand.", "Я не понимаю.", ""}, {12, "See you later.", "Увидимся позже.", ""}, {13, "Excuse me.", "Извините.", ""}, {14, "Let's go.", "Пойдем.", ""}, {15, "Happy birthday!", "С днем рождения!", ""},
        {16, "Could you repeat that, please?", "Не могли бы вы повторить это, пожалуйста?", ""}, {17, "I am looking for a good restaurant.", "Я ищу хороший ресторан.", ""}, {18, "How much does this cost?", "Сколько это стоит?", ""}, {19, "I would like to buy a ticket.", "Я хотел бы купить билет.", ""}, {20, "The train arrives at platform 5.", "Поезд прибывает на 5 платформу.", ""},
        {21, "What are your hobbies?", "Какие у тебя хобби?", ""}, {22, "I enjoy reading and hiking.", "Мне нравится читать и ходить в походы.", ""}, {23, "This food is delicious.", "Эта еда очень вкусная.", ""}, {24, "Where is the nearest supermarket?", "Где находится ближайший супермаркет?", ""}, {25, "I have been studying English for two years.", "Я изучаю английский два года.", ""},
        {26, "My favorite color is blue.", "Мой любимый цвет - синий.", ""}, {27, "Can I have the menu, please?", "Можно мне меню, пожалуйста?", ""}, {28, "I'm sorry, I'm late.", "Извините, я опоздал.", ""}, {29, "What do you recommend?", "Что вы порекомендуете?", ""}, {30, "Have a nice trip!", "Хорошей поездки!", ""},
        {31, "She works as a software engineer.", "Она работает инженером-программистом.", ""}, {32, "He is interested in ancient history.", "Он интересуется древней историей.", ""}, {33, "We are planning a vacation to Italy.", "Мы планируем отпуск в Италию.", ""}, {34, "It's important to stay hydrated.", "Важно пить достаточно воды.", ""}, {35, "They recently bought a new apartment.", "Они недавно купили новую квартиру.", ""},
        {36, "The museum is open from 9 AM to 5 PM.", "Музей открыт с 9 утра до 5 вечера.", ""}, {37, "I prefer coffee to tea in the morning.", "Утром я предпочитаю кофе чаю.", ""}, {38, "Learning a new language can be challenging but rewarding.", "Изучение нового языка может быть сложным, но приносящим удовлетворение.", ""}, {39, "Could you speak a little slower, please?", "Не могли бы вы говорить немного медленнее, пожалуйста?", ""}, {40, "Thank you for your hospitality.", "Спасибо за ваше гостеприимство.", ""}
    };
    grammarTasksMap["Medium"] = {
        {1, "If I ___ you, I would study harder.", {"am", "was", "were", "be"}, "were", ""}, {2, "This book is much ___ than the other one.", {"interesting", "more interesting", "interestinger", "most interesting"}, "more interesting", ""}, {3, "She ___ a book when I called.", {"reads", "read", "was reading", "is reading"}, "was reading", ""}, {4, "They ___ us next week.", {"visit", "visits", "will visit", "visited"}, "will visit", ""}, {5, "I have ___ seen this movie.", {"already", "yet", "still", "ever"}, "already", ""},
        {6, "He ___ to Paris twice.", {"is", "has been", "was", "will be"}, "has been", ""}, {7, "This is the ___ day of my life.", {"good", "better", "best", "most good"}, "best", ""}, {8, "Mount Everest is ___ mountain in the world.", {"high", "higher", "the highest", "most high"}, "the highest", ""}, {9, "The keys are ___ the table.", {"in", "on", "under", "at"}, "on", ""}, {10, "We walked ___ the park.", {"on", "in", "through", "over"}, "through", ""},
        {11, "You ___ see a doctor if you feel sick.", {"can", "may", "should", "must"}, "should", ""}, {12, "She ___ speak three languages fluently.", {"can", "may", "should", "must"}, "can", ""}, {13, "He is taller ___ his brother.", {"as", "so", "than", "then"}, "than", ""}, {14, "Could you pass ___ salt, please?", {"a", "an", "the", "some"}, "the", ""}, {15, "I prefer tea ___ coffee.", {"than", "from", "to", "over"}, "to", ""},
        {16, "They haven't finished their homework ___.", {"already", "yet", "still", "ever"}, "yet", ""}, {17, "This cake was ___ by my mother.", {"make", "makes", "made", "making"}, "made", ""}, {18, "If it ___, we will stay at home.", {"rain", "rains", "rained", "is raining"}, "rains", ""}, {19, "She asked me ___ I was going.", {"that", "if", "what", "which"}, "if", ""}, {20, "He is used to ___ early.", {"get up", "gets up", "getting up", "got up"}, "getting up", ""},
        {21, "I look forward to ___ you soon.", {"see", "sees", "seeing", "saw"}, "seeing", ""}, {22, "This is the house ___ I was born.", {"that", "which", "where", "who"}, "where", ""}, {23, "He plays the guitar ___ than his sister.", {"good", "better", "best", "well"}, "better", ""}, {24, "We should ___ for the exam.", {"study", "studies", "studying", "studied"}, "study", ""}, {25, "While I ___ dinner, the phone rang.", {"cook", "cooked", "was cooking", "am cooking"}, "was cooking", ""},
        {26, "I ___ here since 2010.", {"live", "lived", "have lived", "am living"}, "have lived", ""}, {27, "The car ___ stolen last night.", {"is", "was", "has been", "had been"}, "was", ""}, {28, "She needs ___ some groceries.", {"buy", "to buy", "buying", "bought"}, "to buy", ""}, {29, "This is the ___ interesting book I have ever read.", {"less", "least", "more", "most"}, "most", ""}, {30, "He admitted ___ the mistake.", {"make", "to make", "making", "made"}, "making", ""},
        {31, "They decided ___ a new house.", {"buy", "to buy", "buying", "bought"}, "to buy", ""}, {32, "We might ___ to the party if we finish our work.", {"go", "goes", "going", "went"}, "go", ""}, {33, "She can't help ___ when she watches that movie.", {"cry", "to cry", "crying", "cried"}, "crying", ""}, {34, "It's ___ cold to go swimming today.", {"so", "such", "too", "very"}, "too", ""}, {35, "He promised ___ her with her project.", {"help", "to help", "helping", "helped"}, "to help", ""},
        {36, "The film was ___ exciting that I watched it twice.", {"so", "such", "too", "very"}, "so", ""}, {37, "I've never been ___ China.", {"in", "on", "to", "at"}, "to", ""}, {38, "Would you mind ___ the window?", {"open", "to open", "opening", "opened"}, "opening", ""}, {39, "This situation is getting ___ and ___ complicated.", {"more/more", "most/most", "much/much", "many/many"}, "more/more", ""}, {40, "You must ___ quiet in the library.", {"be", "to be", "being", "been"}, "be", ""}
    };
    timeLimits["Medium"] = 180;

    translationTasksMap["Hard"] = {
        {1, "The quick brown fox jumps over the lazy dog.", "Быстрая коричневая лиса прыгает через ленивую собаку.", ""}, {2, "To be or not to be, that is the question.", "Быть или не быть, вот в чем вопрос.", ""}, {3, "All that glitters is not gold.", "Не все то золото, что блестит.", ""}, {4, "It's raining cats and dogs.", "Льет как из ведра.", ""}, {5, "Could you please tell me the way to the station?", "Не могли бы вы подсказать дорогу к вокзалу?", ""},
        {6, "I look forward to hearing from you soon.", "С нетерпением жду вашего ответа в ближайшее время.", ""}, {7, "Actions speak louder than words.", "Дела говорят громче слов.", ""}, {8, "Rome wasn't built in a day.", "Рим не за один день строился.", ""}, {9, "Let's cross that bridge when we come to it.", "Давай решать проблемы по мере их поступления.", ""}, {10, "Despite the numerous challenges, we remain optimistic about the future.", "Несмотря на многочисленные трудности, мы сохраняем оптимизм в отношении будущего.", ""},
        {11, "The conference addressed pivotal issues concerning sustainable development.", "На конференции рассматривались ключевые вопросы, касающиеся устойчивого развития.", ""}, {12, "She eloquently articulated her position on the matter.", "Она красноречиво изложила свою позицию по этому вопросу.", ""}, {13, "Technological advancements have revolutionized the way we communicate.", "Технологические достижения коренным образом изменили способы нашего общения.", ""}, {14, "One must persevere in the face of adversity to achieve one's goals.", "Нужно упорствовать перед лицом невзгод, чтобы достичь своих целей.", ""}, {15, "The intricate plot of the novel kept readers engaged until the very end.", "Запутанный сюжет романа держал читателей в напряжении до самого конца.", ""},
        {16, "He has a propensity for exaggerating even minor incidents.", "У него есть склонность преувеличивать даже незначительные происшествия.", ""}, {17, "Environmental conservation is paramount for the well-being of future generations.", "Сохранение окружающей среды имеет первостепенное значение для благополучия будущих поколений.", ""}, {18, "The ubiquitous nature of social media has profoundly impacted societal norms.", "Повсеместное распространение социальных сетей оказало глубокое влияние на общественные нормы.", ""}, {19, "It is imperative to conduct thorough research before drawing any conclusions.", "Крайне важно провести тщательное исследование, прежде чем делать какие-либо выводы.", ""}, {20, "The amalgamation of diverse cultures enriches a society.", "Слияние разнообразных культур обогащает общество.", ""},
        {21, "Her dissertation meticulously examines the socio-economic factors.", "Ее диссертация тщательно исследует социально-экономические факторы.", ""}, {22, "The dilapidated building was eventually demolished after years of neglect.", "Ветхое здание было в конечном итоге снесено после многих лет запустения.", ""}, {23, "Negotiations between the two countries reached an impasse.", "Переговоры между двумя странами зашли в тупик.", ""}, {24, "The company's financial woes were exacerbated by the economic downturn.", "Финансовые трудности компании усугубились экономическим спадом.", ""}, {25, "A thorough understanding of quantum mechanics requires considerable intellectual effort.", "Глубокое понимание квантовой механики требует значительных интеллектуальных усилий.", ""}
    };
    grammarTasksMap["Hard"] = {
        {1, "He wishes he ___ bought the car earlier.", {"has", "had", "have", "would have"}, "had", ""}, {2, "By this time next year, I ___ my degree.", {"will finish", "will have finished", "finish", "am finishing"}, "will have finished", ""}, {3, "If she ___ harder, she would have passed the exam.", {"studies", "studied", "had studied", "would study"}, "had studied", ""}, {4, "The book ___ by a famous author last year.", {"writes", "wrote", "was written", "is written"}, "was written", ""}, {5, "This house ___ in 1990.", {"builds", "built", "was built", "is built"}, "was built", ""},
        {6, "English ___ all over the world.", {"speaks", "spoke", "is spoken", "was spoken"}, "is spoken", ""}, {7, "He said that he ___ tired the previous day.", {"is", "was", "has been", "had been"}, "was", ""}, {8, "She asked me where I ___ the night before.", {"live", "lived", "had lived", "am living"}, "had lived", ""}, {9, "It is important that he ___ on time for the meeting.", {"arrive", "arrives", "arrived", "will arrive"}, "arrive", ""}, {10, "Not only ___ me, but he also gave me some advice.", {"he helped", "did he help", "he did help", "helped he"}, "did he help", ""},
        {11, "___ I known about your problem, I would have helped.", {"If", "Had", "Should", "Were"}, "Had", ""}, {12, "She is considering ___ abroad for her studies.", {"go", "to go", "going", "went"}, "going", ""}, {13, "The more you study, ___ you will learn.", {"the more", "more", "the most", "much"}, "the more", ""}, {14, "The new regulations, ___ were implemented last month, are quite strict.", {"that", "which", "who", "whom"}, "which", ""}, {15, "I would rather you ___ that to him.", {"not say", "didn't say", "don't say", "hadn't said"}, "didn't say", ""},
        {16, "He seems ___ a bit upset about the news.", {"be", "to be", "being", "was"}, "to be", ""}, {17, "They were made ___ all the cleaning by themselves.", {"do", "to do", "doing", "done"}, "to do", ""}, {18, "It's no use ___ about it now; the decision has been made.", {"complain", "to complain", "complaining", "complained"}, "complaining", ""}, {19, "Rarely ___ such a beautiful sunset.", {"I have seen", "have I seen", "I saw", "did I see"}, "have I seen", ""}, {20, "Despite ___ tired, he continued working on the project.", {"being", "to be", "was", "be"}, "being", ""},
        {21, "No sooner ___ the news than she burst into tears.", {"she heard", "did she hear", "had she heard", "she had heard"}, "had she heard", ""}, {22, "The committee suggested that the proposal ___ reconsidered.", {"is", "be", "was", "should"}, "be", ""}, {23, "He is ___ a talented musician ___ a gifted painter.", {"either/or", "neither/nor", "both/and", "not only/but also"}, "not only/but also", ""}, {24, "Had it not been for his help, we ___ failed.", {"would", "will have", "would have", "had"}, "would have", ""}, {25, "She insisted on ___ before sunset.", {"leave", "to leave", "leaving", "left"}, "leaving", ""}
    };
    timeLimits["Hard"] = 240;
}

const QList<TranslationTask>& ExerciseData::getTranslationTasks(const QString& difficulty) const {
    auto it = translationTasksMap.constFind(difficulty);
    if (it != translationTasksMap.constEnd()) {
        return *it;
    }
    return emptyTranslationTasks;
}

const QList<GrammarTask>& ExerciseData::getGrammarTasks(const QString& difficulty) const {
    auto it = grammarTasksMap.constFind(difficulty);
    if (it != grammarTasksMap.constEnd()) {
        return *it;
    }
    return emptyGrammarTasks;
}

int ExerciseData::getTimeLimit(const QString& difficulty) const {
    return timeLimits.value(difficulty, 180);
}

const QStringList& ExerciseData::getDifficultyLevels() const {
    return difficultyLevels;
}
